image: docker:latest

variables:
  REPOSITORY_URL: chihuahuah/docker-app
  IMAGE_TAG: latest

services:
- docker:dind

before_script:
  - docker login --username=$DH_USERNAME --password=$DH_PASSWORD

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the image..."
    - docker build
      -t docker-app:latest
      --build-arg PORT=sPORT
      --no-cache .
      - echo "Tagging image..."
    - docker tad docker-app:latest $REPOSITORY_URL:latest
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
    only:
      - master

deploy:
  stage: deploy
  script:
    - docker stop docker-app || true && docker rm docker-app || true
    - docker container run -dt -p $PORT:$PORT --name docker-app $REPOSITORY_URL:latest
    - docker image prune -f
  only:
    - master